### ISSUE TITLE
cannot add new calendar, not pop up the windows

### ISSUE THREAD

**Issue by rubenszolt** [fasterit/roundcube_calendar#19]
Hi, I cannot ad an new calendar, I install the plugin step by step, I have a fresh install debian 9.0.1 with php 7.0. I receive the next error messages

[11-Sep-2017 15:46:18 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 15:46:18 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:46:18 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 15:46:18 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:46:18 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:46:19 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:46:36 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 15:46:36 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:46:36 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 15:46:36 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:46:36 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:46:37 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:47:02 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:47:06 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:47:27 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:47:27 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Personal'
       WHERE categories='Personal'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Work'
       WHERE categories='Work'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Family'
       WHERE categories='Family'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Holiday'
       WHERE categories='Holiday'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:47:49 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:47:55 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 15:47:55 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:47:55 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 15:47:55 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:47:55 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:47:57 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:48:04 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 15:48:04 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:48:04 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 15:48:04 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:48:04 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:48:05 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:49:05 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:51:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 15:51:06 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:51:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 15:51:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 15:51:06 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 15:51:08 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:51:22 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 15:51:22 +0200]: <u5vmopq3> PHP Error: No driver name found in GPC. (GET /webmail/?_task=calendar&_action=load_events&source=1&start=1505080800&end=1505685600&_=1505137882258)
[11-Sep-2017 16:00:08 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:02:08 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:05:56 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:05:56 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:05:56 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:05:56 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:05:56 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:05:59 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:06:12 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:06:12 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:06:50 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:06:50 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:06:50 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:06:50 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:06:50 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:06:51 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:07:11 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:07:11 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:07:14 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:07:51 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:08:16 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:08:16 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Personal'
       WHERE categories='Personal'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Work'
       WHERE categories='Work'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Family'
       WHERE categories='Family'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Holiday'
       WHERE categories='Holiday'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:08:26 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Personal'
       WHERE categories='Personal'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Work'
       WHERE categories='Work'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Family'
       WHERE categories='Family'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Holiday'
       WHERE categories='Holiday'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:08:32 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:08:37 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:08:37 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:08:37 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:08:37 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:08:37 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:08:38 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:08:38 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:18:51 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:18:51 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Personal'
       WHERE categories='Personal'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Work'
       WHERE categories='Work'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Family'
       WHERE categories='Family'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 4 (SQL Query: UPDATE caldav_events
       SET   categories='Holiday'
       WHERE categories='Holiday'
       AND   calendar_id IN ()) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /webmail/?_task=settings&_action=save-prefs)
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:19:02 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:19:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:19:06 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:19:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:19:06 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:19:06 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:19:07 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:21:07 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:22:45 Europe/Berlin] PHP Parse error:  syntax error, unexpected '?>', expecting ')' in /usr/share/roundcube/plugins/calendar/config.inc.php on line 198
[11-Sep-2017 16:23:03 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method caldav_driver::insert_default_calendar() in /usr/share/roundcube/plugins/calendar/calendar.php:182
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->startup(Array)
#1 /usr/share/roundcube/index.php(87): rcube_plugin_api->exec_hook('startup', Array)
#2 {main}
  thrown in /usr/share/roundcube/plugins/calendar/calendar.php on line 182
[11-Sep-2017 16:23:19 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method caldav_driver::insert_default_calendar() in /usr/share/roundcube/plugins/calendar/calendar.php:182
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->startup(Array)
#1 /usr/share/roundcube/index.php(87): rcube_plugin_api->exec_hook('startup', Array)
#2 {main}
  thrown in /usr/share/roundcube/plugins/calendar/calendar.php on line 182
[11-Sep-2017 16:23:34 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:23:34 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:23:34 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:23:34 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:23:34 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:23:36 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:24:32 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method caldav_driver::insert_default_calendar() in /usr/share/roundcube/plugins/calendar/calendar.php:182
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->startup(Array)
#1 /usr/share/roundcube/index.php(87): rcube_plugin_api->exec_hook('startup', Array)
#2 {main}
  thrown in /usr/share/roundcube/plugins/calendar/calendar.php on line 182
[11-Sep-2017 16:24:55 Europe/Berlin] PHP Parse error:  syntax error, unexpected '?>', expecting ')' in /usr/share/roundcube/plugins/calendar/config.inc.php on line 198
[11-Sep-2017 16:25:20 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method caldav_driver::insert_default_calendar() in /usr/share/roundcube/plugins/calendar/calendar.php:182
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->startup(Array)
#1 /usr/share/roundcube/index.php(87): rcube_plugin_api->exec_hook('startup', Array)
#2 {main}
  thrown in /usr/share/roundcube/plugins/calendar/calendar.php on line 182
[11-Sep-2017 16:25:25 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method caldav_driver::insert_default_calendar() in /usr/share/roundcube/plugins/calendar/calendar.php:182
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->startup(Array)
#1 /usr/share/roundcube/index.php(87): rcube_plugin_api->exec_hook('startup', Array)
#2 {main}
  thrown in /usr/share/roundcube/plugins/calendar/calendar.php on line 182
[11-Sep-2017 16:25:52 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[11-Sep-2017 16:25:52 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[11-Sep-2017 16:25:52 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[11-Sep-2017 16:25:52 +0200]: <u5vmopq3> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[11-Sep-2017 16:25:52 +0200]: <u5vmopq3> Warning: Call to deprecated function Q(); See bc.inc for replacement
[11-Sep-2017 16:25:54 +0200]: <u5vmopq3> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement

**Comment by rubenszolt** [comment]
I tested on new instalation, similar with previous. I install step by step when is described but same issue, 
I cannot ad an new calendar, not pop up the window to can add new calendar , I tested on Chrome and Firefox.

I use Roundcube Webmail 1.2.3 version, from Debian stable repo.

I attach the roundcube error.log

[25-Oct-2017 11:55:10 Europe/Berlin] PHP Warning:  Declaration of kolab_driver::get_event_diff($event, $rev1, $rev2) should be compatible with calendar_driver::get_event_diff($event, $rev) in /usr/share/roundcube/plugins/calendar/drivers/kolab/kolab_driver.php on line 0
[25-Oct-2017 11:55:10 +0200]: <ubhgules> PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/libkolab/libkolab.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /webmail/?_task=calendar)
[25-Oct-2017 11:55:10 +0200]: <ubhgules> PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/libkolab/libkolab.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /webmail/?_task=calendar)
[25-Oct-2017 11:55:10 Europe/Berlin] PHP Fatal error:  Class 'kolab_storage_folder_api' not found in /usr/share/roundcube/plugins/calendar/drivers/kolab/kolab_calendar.php on line 27
[25-Oct-2017 11:56:14 Europe/Berlin] PHP Warning:  Declaration of kolab_driver::get_event_diff($event, $rev1, $rev2) should be compatible with calendar_driver::get_event_diff($event, $rev) in /usr/share/roundcube/plugins/calendar/drivers/kolab/kolab_driver.php on line 0
[25-Oct-2017 11:56:14 +0200]: <ubhgules> PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/libkolab/libkolab.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (POST /webmail/?_task=mail&_action=refresh)
[25-Oct-2017 11:56:14 +0200]: <ubhgules> PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/libkolab/libkolab.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (POST /webmail/?_task=mail&_action=refresh)
[25-Oct-2017 11:56:14 Europe/Berlin] PHP Fatal error:  Class 'kolab_storage_folder_api' not found in /usr/share/roundcube/plugins/calendar/drivers/kolab/kolab_calendar.php on line 27
[25-Oct-2017 11:57:01 +0200]: <ubhgules> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[25-Oct-2017 11:57:01 +0200]: <ubhgules> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 11:57:01 +0200]: <ubhgules> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[25-Oct-2017 11:57:01 +0200]: <ubhgules> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[25-Oct-2017 11:57:01 +0200]: <ubhgules> Warning: Call to deprecated function Q(); See bc.inc for replacement
[25-Oct-2017 11:57:02 +0200]: <ubhgules> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 11:59:01 +0200]: <ubhgules> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function rcube_autocomplete_init(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function rcube_upload_init(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function Q(); See bc.inc for replacement
[25-Oct-2017 12:00:42 +0200]: <pk1cv32i> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:00:51 +0200]: <pk1cv32i> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:00:59 +0200]: <pk1cv32i> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:01:04 +0200]: <pk1cv32i> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement
[25-Oct-2017 12:01:10 +0200]: <pk1cv32i> Warning: Call to deprecated function Q(); See bc.inc for replacement
[25-Oct-2017 12:01:10 +0200]: <pk1cv32i> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement

**Comment by rubenszolt** [comment]
Hi, any update?

**Comment by fr87** [comment]
Same issue here. Were you able to resolve it?

**Comment by Offerel** [comment]
My solution was it, to write [my own plugin](https://github.com/Offerel/roundcube_caldavzap). It does not sync, but it can connect to a CalDAV Server on same domain and i can view and add events and Todos. I didn't need more currently.

**Comment by hermawan-fsi** [comment]
still wonder where i can put user name and password for my postgresql
this isi error. i found 
Nov  7 08:27:10 mail roundcube: <brpnl2bb> DB Error: [7] ERROR:  permission denied for relation calendars (SQL Query: SELECT *, calendar_id AS id FROM calendars#012
