### ISSUE TITLE
not working, roundcube 1.3.6, empty settings page, empty calendar page, Call to undefined function rcube_autocomplete_init(), need patch from another repo

### ISSUE THREAD

**Issue by pafcioooo** [fasterit/roundcube_calendar#21]
1. I have done everything according to installation guide:
- clone the repo
- copied calendar and libcalendaring to plugins
- edited config.inc.php in plugins/calendar
- run two sql scripts against mysql
- enabled plugin in config/config.inc.php
2. After I enter roundcube 
- there is an icon for calendar in menu, but when I click it empty page displays
- there is an calendar options is settings, but when I choose it it says "loading" but nothing displays eventually
- on the list of emails, emails with calendar invitations are marked with calendar icon but clicking it does nothing - no preview
- no error in apache error log

**Comment by pafcioooo** [comment]
Ok I forgot to look into roundcube/logs/errors, here is:

```
[27-Jun-2018 21:04:24 Europe/Warsaw] PHP Parse error:  syntax error, unexpected '?>', expecting ')' in /home/poczta/public_html/roundcubemail/plugins/calendar/config.inc.php on line 214
[27-Jun-2018 21:04:50 Europe/Warsaw] PHP Parse error:  syntax error, unexpected '?>', expecting ')' in /home/poczta/public_html/roundcubemail/plugins/calendar/config.inc.php on line 214
[27-Jun-2018 21:06:36 Europe/Warsaw] PHP Parse error:  syntax error, unexpected '?>', expecting ')' in /home/poczta/public_html/roundcubemail/plugins/calendar/config.inc.php on line 214
[27-Jun-2018 21:09:11 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function Q() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:2898
Stack trace:
#0 /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php(2961): calendar->mail_agenda_event_row(Array, 'current')
#1 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(440): calendar->mail_messagebody_html(Array)
#2 /home/poczta/public_html/roundcubemail/program/include/rcmail_output_html.php(1208): rcube_plugin_api->exec_hook('template_object...', Array)
#3 [internal function]: rcmail_output_html->xml_command(Array)
#4 /home/poczta/public_html/roundcubemail/program/include/rcmail_output_html.php(1013): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#5 /home/poczta/public_html/roundcubemail/program/include/rcmail_output_html.php(634): rcmail_output_html->parse_xml('<roundcube:obje...')
#6 /home/poczta/public_html/roundcubemail/program/include/rcmail_output_html.php(488): rcmail_output_html->parse('messag in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 2898
[27-Jun-2018 21:09:32 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function rcube_autocomplete_init() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:498
Stack trace:
#0 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(493): calendar->calendar_view()
#1 /home/poczta/public_html/roundcubemail/index.php(295): rcube_plugin_api->exec_action('calendar.index')
#2 /home/poczta/public_html/roundcubemail/public_html/index.php(26): include('/home/poczta/pu...')
#3 {main}
  thrown in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 498
[27-Jun-2018 21:09:49 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function Q() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:565
Stack trace:
#0 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(440): calendar->preferences_list(Array)
#1 /home/poczta/public_html/roundcubemail/program/steps/settings/func.inc(1265): rcube_plugin_api->exec_hook('preferences_lis...', Array)
#2 /home/poczta/public_html/roundcubemail/program/steps/settings/edit_prefs.inc(28): rcmail_user_prefs('calendar')
#3 /home/poczta/public_html/roundcubemail/index.php(303): include_once('/home/poczta/pu...')
#4 /home/poczta/public_html/roundcubemail/public_html/index.php(26): include('/home/poczta/pu...')
#5 {main}
  thrown in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 565
[27-Jun-2018 21:18:35 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function rcube_autocomplete_init() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:498
Stack trace:
#0 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(493): calendar->calendar_view()
#1 /home/poczta/public_html/roundcubemail/index.php(295): rcube_plugin_api->exec_action('calendar.index')
#2 /home/poczta/public_html/roundcubemail/public_html/index.php(26): include('/home/poczta/pu...')
#3 {main}
  thrown in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 498
[27-Jun-2018 21:19:16 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function Q() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:565
Stack trace:
#0 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(440): calendar->preferences_list(Array)
#1 /home/poczta/public_html/roundcubemail/program/steps/settings/func.inc(1265): rcube_plugin_api->exec_hook('preferences_lis...', Array)
#2 /home/poczta/public_html/roundcubemail/program/steps/settings/edit_prefs.inc(28): rcmail_user_prefs('calendar')
#3 /home/poczta/public_html/roundcubemail/index.php(303): include_once('/home/poczta/pu...')
#4 /home/poczta/public_html/roundcubemail/public_html/index.php(26): include('/home/poczta/pu...')
#5 {main}
  thrown in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 565
```

**Comment by pafcioooo** [comment]
There was ?> entry in plugins/calendar/config.inc.php (which is also in .dist file). I have removed it.
Now symptoms are the same, but in roundcube/logs/errors there is only this:
```
[27-Jun-2018 21:26:16 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function rcube_autocomplete_init() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:498
Stack trace:
[27-Jun-2018 21:26:16 Europe/Warsaw] PHP Fatal error:  Uncaught Error: Call to undefined function rcube_autocomplete_init() in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php:498
Stack trace:
#0 /home/poczta/public_html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(493): calendar->calendar_view()
#1 /home/poczta/public_html/roundcubemail/index.php(295): rcube_plugin_api->exec_action('calendar.index')
#2 /home/poczta/public_html/roundcubemail/public_html/index.php(26): include('/home/poczta/pu...')
#3 {main}
  thrown in /home/poczta/public_html/roundcubemail/plugins/calendar/calendar.php on line 498
```

**Comment by pafcioooo** [comment]
If I search github for the rcube_autocomplete_init() it find this in bc.php file which was part of roundcube/program/include folder but in 1.3.6 the is no such file.

**Comment by pafcioooo** [comment]
I found #19 and #15 had similiar problems. Esspecially in #15  it is mentioned that there are some patches for version 1.3 of Roundcube, but it seems that thay are not put into this repository and mentioned there repository https://gitlab.awesome-it.de/kolab/roundcube-plugins/commit/967eac96c7b898cf44ba7193815117fc2aac618d is unavailable.

**Comment by pafcioooo** [comment]
OK. So in #15 @fasterit pointed me to a new repo https://github.com/dotplex/roundcube_calendar that has Roundcube 1.3.x patch.
After applying files from this repo:
1. What is working:
- calendar pages are being displayed as it should.
- I was able to add external caldav calendar (from EasyRedmine)
- When emails with calendar invitations are clicked I see the invitation - I can see agenda from calendar (which is awesome)
- in calendar invitation if I accept invitation it is added to calendar
2. What is not working
- in calendar invitation, calendar check does not work. It opens a browser windows with error "
SERVICE CURRENTLY NOT AVAILABLE! Error No. [500]"
- in calendar invitation, after I click accept, and then click "update in my calendar" it shows error "Application Error (500) no driver found for calendar "" "

**Comment by pafcioooo** [comment]
It works, which is excellent write now, so I close the issue. Errors will go into new issues.

**Comment by pafcioooo** [comment]
One more thing.
I do not know but suddenly both not working in 2. are working.
So problem solved to the bones;-)

**Comment by pafcioooo** [comment]
Still sometimes it happens that:

   - in calendar invitation, calendar check does not work. It opens a browser windows with error "
    SERVICE CURRENTLY NOT AVAILABLE! Error No. [500]"
   - in calendar invitation, after I click accept, and then click "update in my calendar" it shows error "Event coould not be imported"
